# These are supported funding model platforms

github: [adityajanjanam]  # GitHub Sponsors (if you set this up)
buy_me_a_coffee: adityajanjanam  # Buy Me a Coffee profile
custom: ['https://linktr.ee/adityajanjanam']  # Linktree profile with additional links
